import React from 'react';
import '../styles/globals.scss';
import Image from 'next/image';
import Head from 'next/head';
import Header from '../components/Header/Header';
import Nav from '../components/Header/Nav';
import style from '../styles/style.module.css';

function MyApp({ Component, pageProps }) {
  return (
    <div className={ style.container }>
      <Head>
        <title>Dashboard Bagy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <main className={ style.main }>
        <Component { ...pageProps } />
      </main>
      <footer className={ style.footer }>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Bagy
          { ' ' }
          <span className={ style.logo }>
            <Image src="/bagyicon.svg" alt="Vercel Logo" width={ 32 } height={ 32 } />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default MyApp;
